#!/bin/bash
#flask --app main run --host=0.0.0.0 --port=5000 --with-threads --reload
#use local python version
# comment this script if you don't have pyenv
# pyenv local 3.10.10
# pyenv rehash
# end comment

#using venv
source myenv/bin/activate

flask --app main run --port=5000 --with-threads --reload