#!/bin/bash
# make sure you have pyenv installed
# uncomment to install

#pyenv install 3.10.10
#pyenv rehash


# use local python version
pyenv local 3.10.10

# use global python version
# pyenv global 3.10.10

#use venv
source myenv/bin/activate

# install cmake ubuntu
sudo apt install cmake
1. Install dependencies:
2. Create a virtual environment:
   ```
   python3 -m venv myenv
   ```

3. Activate the virtual environment:
   On Windows:
   ```
   myenv\Scripts\activate
   ```
   On MacOS/Linux:
   ```
   source myenv/bin/activate
   ```

4. Install the required dependencies:
   ```
   pip install -r requirements.txt
   ```

5. Run the application:
   ```
   flask run
   ```
# install pip requirements
pip install --upgrade pip setuptools wheel
pip install -r requirements.txt
